load("//bazel:build_system.bzl", "strij_cc_library")

strij_cc_library(
    name = "task_handlers_interface",
    hdrs = ["task_handlers.hh"],
    visibility = ["//visibility:public"],
    deps = [
        "//api/common/node:node_cc_proto",
        "//api/common/task:task_cc_proto",
        "//include/strij/extensions:extension_registry_lib",
        "//include/strij/extensions:factory_context_lib",
        "@abseil-cpp//absl/status:statusor",
        "@protobuf",
    ],
)
