load("@protobuf//bazel:cc_proto_library.bzl", "cc_proto_library")
load("@rules_proto//proto:defs.bzl", "proto_library")

proto_library(
    name = "round_robin_scheduler_proto",
    srcs = ["round_robin.proto"],
    strip_import_prefix = "/api",
    visibility = ["//visibility:public"],
)

cc_proto_library(
    name = "round_robin_scheduler_cc_proto",
    visibility = ["//visibility:public"],
    deps = [":round_robin_scheduler_proto"],
)
