load("//bazel:build_system.bzl", "carrot_cc_library")

carrot_cc_library(
    name = "tlv_frame",
    hdrs = ["tlv_frame.hh"],
    visibility = ["//visibility:public"],
)

carrot_cc_library(
    name = "protocol_parser",
    hdrs = ["protocol_parser.hh"],
)

carrot_cc_library(
    name = "chunk_lib",
    srcs = ["chunk.cc"],
    hdrs = ["chunk.hh"],
)

carrot_cc_library(
    name = "llhttp_parser_lib",
    srcs = ["llhttp_parser.cc"],
    hdrs = ["llhttp_parser.hh"],
    visibility = ["//visibility:public"],
    deps = [
        ":chunk_lib",
        ":protocol_parser",
        "//:llhttp",
        "//src/core/logging:log_lib",
    ],
)

carrot_cc_library(
    name = "tlv_parser_lib",
    srcs = ["tlv_parser.cc"],
    hdrs = ["tlv_parser.hh"],
    visibility = ["//visibility:public"],
    deps = [
        ":protocol_parser",
        ":tlv_frame",
        "//src/core/logging:log_lib",
    ],
)

carrot_cc_library(
    name = "connection_lib",
    srcs = ["connection.cc"],
    hdrs = ["connection.hh"],
    deps = [
        ":protocol_parser",
        "//include/carrot/event:dispatcher_interface",
        "//include/carrot/event:io_object_interface",
    ],
)

carrot_cc_library(
    name = "result_receiver_storage",
    hdrs = ["result_receiver_storage.hh"],
    visibility = ["//visibility:public"],
)

carrot_cc_library(
    name = "echo_result_receiver_lib",
    srcs = ["echo_result_receiver.cc"],
    hdrs = ["echo_result_receiver.hh"],
    visibility = ["//visibility:public"],
    deps = [
        ":connection_lib",
        ":result_receiver_storage",
    ],
)

carrot_cc_library(
    name = "gateway_http_handler_lib",
    srcs = ["gateway_http_handler.cc"],
    hdrs = ["gateway_http_handler.hh"],
    visibility = ["//visibility:public"],
    deps = [
        ":connection_lib",
        ":result_receiver_storage",
        ":tlv_frame",
        "//src/core/logging:log_lib",
    ],
)

carrot_cc_library(
    name = "gateway_tlv_handler_lib",
    srcs = ["gateway_tlv_handler.cc"],
    hdrs = ["gateway_tlv_handler.hh"],
    visibility = ["//visibility:public"],
    deps = [
        ":connection_lib",
        ":result_receiver_storage",
        ":tlv_frame",
        "//src/core/logging:log_lib",
    ],
)

carrot_cc_library(
    name = "nodeagent_tlv_handler_lib",
    srcs = ["nodeagent_tlv_handler.cc"],
    hdrs = ["nodeagent_tlv_handler.hh"],
    visibility = ["//visibility:public"],
    deps = [
        ":connection_lib",
        ":tlv_frame",
    ],
)

carrot_cc_library(
    name = "tcp_listener_lib",
    srcs = ["tcp_listener.cc"],
    hdrs = ["tcp_listener.hh"],
    visibility = ["//visibility:public"],
    deps = [
        ":connection_lib",
        "//src/core/logging:log_lib",
    ],
)

carrot_cc_library(
    name = "tcp_connector_lib",
    srcs = ["tcp_connector.cc"],
    hdrs = ["tcp_connector.hh"],
    visibility = ["//visibility:public"],
    deps = [
        ":connection_lib",
        ":gateway_tlv_handler_lib",
        ":tlv_parser_lib",
        "//src/core/logging:log_lib",
    ],
)
