load("//bazel:build_system.bzl", "carrot_cc_library")

carrot_cc_library(
    name = "static_node_discovery_lib",
    srcs = ["static_node_discovery.cc"],
    hdrs = ["static_node_discovery.hh"],
    visibility = ["//visibility:public"],
    deps = [
        "//api/extensions/node_discovery/static:static_node_discovery_cc_proto",
        "//src/extensions/node_discovery:node_discovery_interface",
    ],
    alwayslink = True,
)
