load("//bazel:build_system.bzl", "strij_cc_library")

strij_cc_library(
    name = "command_interface",
    hdrs = ["command.hh"],
    visibility = ["//visibility:public"],
)

strij_cc_library(
    name = "dispatcher_interface",
    hdrs = ["dispatcher.hh"],
    visibility = ["//visibility:public"],
    deps = [
        ":command_interface",
        "//include/strij/common:pure_lib",
    ],
)

strij_cc_library(
    name = "completable_interface",
    hdrs = ["completable.hh"],
    visibility = ["//visibility:public"],
    deps = [
        "//include/strij/common:pure_lib",
    ],
)

strij_cc_library(
    name = "command_handler_interface",
    hdrs = ["command_handler.hh"],
    visibility = ["//visibility:public"],
    deps = [
        ":command_interface",
        "//include/strij/common:pure_lib",
    ],
)
