load("//bazel:build_system.bzl", "strij_cc_test")

strij_cc_test(
    name = "capability_aware_scheduler_test",
    srcs = ["capability_aware_scheduler_test.cc"],
    deps = [
        "//api/core/node:node_cc_proto",
        "//api/core/task:task_cc_proto",
        "//src/core/gateway:node_directory_lib",
        "//src/extensions/schedulers/capability_aware:capability_aware_scheduler_lib",
        "//src/extensions/schedulers:scheduler_interface",
        "//test/mocks/common:common_mocks_lib",
        "//test/mocks/event:event_mocks_lib",
        "@googletest//:gtest_main",
    ],
)
