load("//bazel:build_system.bzl", "strij_cc_library")

strij_cc_library(
    name = "task_handlers_interface",
    hdrs = ["task_handlers.hh"],
    visibility = ["//visibility:public"],
    deps = [
        "//api/core/node:node_cc_proto",
        "//api/core/task:task_cc_proto",
        "//src/core/extensions:extension_registry_lib",
        "//src/core/extensions:factory_context_lib",
        "@abseil-cpp//absl/status:statusor",
        "@protobuf//:protobuf",
    ],
)
