load("//bazel:build_system.bzl", "strij_cc_library")

strij_cc_library(
    name = "piped_executable_task_handler_lib",
    srcs = [
        "child_process.cc",
        "piped_executable_task_handler.cc",
    ],
    hdrs = [
        "child_process.hh",
        "piped_executable_task_handler.hh",
    ],
    visibility = [
        "//src/nodeagent/exe:__pkg__",
        "//test:__subpackages__",
    ],
    deps = [
        "//api/nodeagent/extensions/task_handlers/piped_executable:piped_executable_cc_proto",
        "//include/strij/event:command_handler_interface",
        "//include/strij/event:completable_interface",
        "//include/strij/event:dispatcher_interface",
        "//include/strij/extensions:extension_registry_lib",
        "//include/strij/nodeagent:task_handlers_interface",
        "//src/common/core/logging:log_lib",
        "//src/nodeagent/core:function_resolver_lib",
        "@abseil-cpp//absl/status",
        "@abseil-cpp//absl/status:statusor",
    ],
    alwayslink = True,
)
