#include "core/utils/task_id.hh"

#include <array>
#include <cstddef>
#include <random>
#include <string>
#include <string_view>

namespace carrot::utils {
namespace {

using namespace std::string_view_literals;

constexpr std::array kAdjectives{
    "able"sv,    "ample"sv,   "ancient"sv, "angry"sv,   "autumn"sv,  "bald"sv,
    "bamboo"sv,  "bare"sv,    "bashful"sv, "bent"sv,    "bitter"sv,  "bland"sv,
    "blazing"sv, "blond"sv,   "bogus"sv,   "bold"sv,    "brave"sv,   "brief"sv,
    "bright"sv,  "brisk"sv,   "brittle"sv, "bronze"sv,  "brown"sv,   "brusque"sv,
    "calm"sv,    "candid"sv,  "carnal"sv,  "causal"sv,  "chilly"sv,  "civic"sv,
    "civil"sv,   "clever"sv,  "cloudy"sv,  "coarse"sv,  "cobalt"sv,  "colder"sv,
    "comic"sv,   "copper"sv,  "cosmic"sv,  "coy"sv,     "crisp"sv,   "crude"sv,
    "crystal"sv, "curly"sv,   "cute"sv,    "dapper"sv,  "dear"sv,    "deep"sv,
    "dense"sv,   "dim"sv,     "dire"sv,    "dizzy"sv,   "dormant"sv, "dotted"sv,
    "drab"sv,    "drafty"sv,  "droll"sv,   "dry"sv,     "dusky"sv,   "eager"sv,
    "early"sv,   "eastern"sv, "easy"sv,    "elder"sv,   "empty"sv,   "even"sv,
    "faint"sv,   "fair"sv,    "fancy"sv,   "fast"sv,    "fatal"sv,   "fearful"sv,
    "feathery"sv,"fickle"sv,  "fierce"sv,  "final"sv,   "firm"sv,    "fixed"sv,
    "flaky"sv,   "flawed"sv,  "fleet"sv,   "floral"sv,  "flush"sv,   "flying"sv,
    "foamy"sv,   "foggy"sv,   "frozen"sv,  "full"sv,    "gaunt"sv,   "gentle"sv,
    "ghostly"sv, "glad"sv,    "glassy"sv,  "glib"sv,    "glossy"sv,  "golden"sv,
    "graceful"sv,"gravel"sv,  "gray"sv,    "great"sv,   "green"sv,   "gruff"sv,
    "grumpy"sv,  "hairy"sv,   "harsh"sv,   "hasty"sv,   "hazel"sv,   "hazy"sv,
    "heavy"sv,   "hidden"sv,  "hollow"sv,  "holy"sv,    "honest"sv,  "hot"sv,
    "husky"sv,   "icy"sv,     "ideal"sv,   "idle"sv,    "ivory"sv,   "jaded"sv,
    "jolly"sv,   "jovial"sv,  "keen"sv,    "kind"sv,    "lame"sv,    "lanky"sv,
    "large"sv,   "lazy"sv,    "leafy"sv,   "lean"sv,    "level"sv,   "light"sv,
    "lilac"sv,   "lively"sv,  "lofty"sv,   "loud"sv,    "lunar"sv,   "lush"sv,
    "mellow"sv,  "merry"sv,   "mild"sv,    "misty"sv,   "mixed"sv,   "moist"sv,
    "moody"sv,   "mossy"sv,   "muddy"sv,   "muted"sv,   "naive"sv,   "narrow"sv,
    "neat"sv,    "needy"sv,   "nervous"sv, "new"sv,     "next"sv,    "nimble"sv,
    "noble"sv,   "northern"sv,"notable"sv, "novel"sv,   "numb"sv,    "obtuse"sv,
    "odd"sv,     "oily"sv,    "old"sv,     "olive"sv,   "opaque"sv,  "open"sv,
    "orange"sv,  "oval"sv,    "pale"sv,    "patient"sv, "pearly"sv,  "plain"sv,
    "plump"sv,   "polite"sv,  "pretty"sv,  "privy"sv,   "prize"sv,   "proud"sv,
    "prudent"sv, "purple"sv,  "quaint"sv,  "quick"sv,   "quiet"sv,   "rainy"sv,
    "rapid"sv,   "rare"sv,    "raw"sv,     "red"sv,     "remote"sv,  "rich"sv,
    "rigid"sv,   "ripe"sv,    "risky"sv,   "rival"sv,   "rosy"sv,    "rough"sv,
    "round"sv,   "royal"sv,   "rueful"sv,  "rural"sv,   "sad"sv,     "safe"sv,
    "salty"sv,   "sandy"sv,   "savvy"sv,   "scarce"sv,  "scared"sv,  "scenic"sv,
    "second"sv,  "secret"sv,  "sharp"sv,   "shiny"sv,   "shy"sv,     "silly"sv,
    "simple"sv,  "sincere"sv, "sleek"sv,   "slim"sv,    "sly"sv,     "small"sv,
    "smug"sv,    "snug"sv,    "sober"sv,   "solar"sv,   "solid"sv,   "sore"sv,
    "sour"sv,    "sparse"sv,  "spicy"sv,   "splendid"sv,"square"sv,  "stable"sv,
    "stale"sv,   "steady"sv,  "steep"sv,   "stern"sv,   "stiff"sv,   "still"sv,
    "stocky"sv,  "stout"sv,   "straight"sv,"strange"sv, "strict"sv,  "sturdy"sv,
    "subtle"sv,  "sudden"sv,  "sulky"sv,   "summer"sv,  "sunny"sv,   "swift"sv,
    "tall"sv,    "tame"sv,    "tan"sv,     "tart"sv,    "taut"sv,    "tepid"sv,
    "thick"sv,   "thin"sv,    "tidy"sv,    "timely"sv,  "tiny"sv,    "tired"sv,
    "tolerant"sv,"tough"sv,   "tranquil"sv,"trim"sv,    "tropical"sv,"true"sv,
    "twin"sv,    "ugly"sv,    "united"sv,  "upper"sv,   "upright"sv, "urban"sv,
    "used"sv,    "vague"sv,   "vain"sv,    "valid"sv,   "vast"sv,    "velvet"sv,
    "violet"sv,  "vivid"sv,   "warm"sv,    "wary"sv,    "wavy"sv,    "waxen"sv,
    "weak"sv,    "weary"sv,   "western"sv, "wet"sv,     "wheat"sv,   "wheezy"sv,
    "whimsy"sv,  "white"sv,   "whole"sv,   "wild"sv,    "wily"sv,    "windy"sv,
    "winter"sv,  "wiry"sv,    "wispy"sv,   "witty"sv,   "woozy"sv,   "worldly"sv,
    "wry"sv,     "youthful"sv,"yummy"sv,   "zany"sv,    "zealous"sv,
};

constexpr std::array kNouns{
    "acorn"sv,     "afternoon"sv, "alder"sv,     "alley"sv,     "alpaca"sv,
    "anemone"sv,   "apple"sv,     "apricot"sv,   "arcade"sv,    "arena"sv,
    "armadillo"sv, "arrow"sv,     "aspen"sv,     "atlas"sv,     "avenue"sv,
    "avocado"sv,   "azalea"sv,    "bacon"sv,     "badger"sv,    "bagel"sv,
    "bamboo"sv,    "banana"sv,    "bandana"sv,   "banner"sv,    "banyan"sv,
    "barn"sv,      "barrel"sv,    "basil"sv,     "basin"sv,     "basket"sv,
    "bass"sv,      "bath"sv,      "bayou"sv,     "beacon"sv,    "bead"sv,
    "beam"sv,      "bean"sv,      "beaver"sv,    "bedrock"sv,   "beetle"sv,
    "bell"sv,      "belly"sv,     "bench"sv,     "berry"sv,     "beverage"sv,
    "bicycle"sv,   "bison"sv,     "blade"sv,     "blanket"sv,   "blaze"sv,
    "blimp"sv,     "blizzard"sv,  "blossom"sv,   "bluff"sv,     "board"sv,
    "bobcat"sv,    "bolt"sv,      "bongo"sv,     "bonnet"sv,    "bonus"sv,
    "bonsai"sv,    "book"sv,      "booth"sv,     "boulder"sv,   "bouquet"sv,
    "bowl"sv,      "box"sv,       "bramble"sv,   "branch"sv,    "brass"sv,
    "breeze"sv,    "brick"sv,     "bridge"sv,    "broccoli"sv,  "brook"sv,
    "broom"sv,     "brush"sv,     "bubble"sv,    "buckle"sv,    "buddy"sv,
    "budget"sv,    "buffalo"sv,   "bugle"sv,     "bulb"sv,      "bulk"sv,
    "bullet"sv,    "bunny"sv,     "bureau"sv,    "burrow"sv,    "bush"sv,
    "butter"sv,    "button"sv,    "cabin"sv,     "cable"sv,     "cactus"sv,
    "cafe"sv,      "cage"sv,      "cake"sv,      "camel"sv,     "camera"sv,
    "camp"sv,      "canal"sv,     "candle"sv,    "canyon"sv,    "cargo"sv,
    "caribou"sv,   "carpet"sv,    "carrot"sv,    "cascade"sv,   "castle"sv,
    "catfish"sv,   "cavern"sv,    "caviar"sv,    "cedar"sv,     "cellar"sv,
    "cello"sv,     "census"sv,    "chalet"sv,    "chalk"sv,     "chamber"sv,
    "champ"sv,     "channel"sv,   "chapel"sv,    "charmer"sv,   "cheese"sv,
    "cherry"sv,    "chest"sv,     "chicken"sv,   "chime"sv,     "chimney"sv,
    "chip"sv,      "chisel"sv,    "chive"sv,     "chocolate"sv, "chorus"sv,
    "chunk"sv,     "cider"sv,     "cinder"sv,    "circus"sv,    "citron"sv,
    "clasp"sv,     "clay"sv,      "cleaver"sv,   "cliff"sv,     "climate"sv,
    "clipper"sv,   "clock"sv,     "closet"sv,    "cloud"sv,     "clover"sv,
    "club"sv,      "coach"sv,     "coast"sv,     "cobbler"sv,   "cocoa"sv,
    "coconut"sv,   "cod"sv,       "coffee"sv,    "coil"sv,      "coin"sv,
    "collar"sv,    "colony"sv,    "column"sv,    "comet"sv,     "comic"sv,
    "compass"sv,   "conch"sv,     "condor"sv,    "cone"sv,      "coral"sv,
    "cord"sv,      "corner"sv,    "corridor"sv,  "cotton"sv,    "cougar"sv,
    "courtyard"sv, "cove"sv,      "coyote"sv,    "crab"sv,      "cradle"sv,
    "crane"sv,     "crate"sv,     "crater"sv,    "creek"sv,     "crest"sv,
    "cricket"sv,   "crimson"sv,   "crocus"sv,    "crystal"sv,   "cub"sv,
    "cuckoo"sv,    "curio"sv,     "curtain"sv,   "curve"sv,     "cushion"sv,
    "cyclone"sv,   "cypress"sv,   "dagger"sv,    "daisy"sv,     "dandelion"sv,
    "danube"sv,    "dawn"sv,      "daybreak"sv,  "desert"sv,    "dew"sv,
    "diadem"sv,    "diamond"sv,   "dill"sv,      "dime"sv,      "dinosaur"sv,
    "dipper"sv,    "dirt"sv,      "ditch"sv,     "diver"sv,     "dock"sv,
    "dolphin"sv,   "dome"sv,      "donkey"sv,    "donor"sv,     "dove"sv,
    "dragon"sv,    "drake"sv,     "drama"sv,     "drape"sv,     "dress"sv,
    "drift"sv,     "drill"sv,     "drink"sv,     "drum"sv,      "duck"sv,
    "dune"sv,      "dusk"sv,      "dust"sv,      "dwarf"sv,     "eagle"sv,
    "earth"sv,     "easel"sv,     "echo"sv,      "eclipse"sv,   "eddy"sv,
    "elm"sv,       "ember"sv,     "emerald"sv,   "engine"sv,    "enigma"sv,
    "envoy"sv,     "epoch"sv,     "equator"sv,   "escal"sv,     "estate"sv,
    "ether"sv,     "evergreen"sv, "explorer"sv,  "fable"sv,     "falcon"sv,
    "fanfare"sv,   "farm"sv,      "faucet"sv,    "fawn"sv,      "feather"sv,
    "fennel"sv,    "ferret"sv,    "ferry"sv,     "fiber"sv,     "fiddle"sv,
    "field"sv,     "fig"sv,       "fillet"sv,    "finch"sv,     "fir"sv,
    "firefly"sv,   "fjord"sv,     "flame"sv,     "flannel"sv,   "flask"sv,
    "flavor"sv,    "flax"sv,      "fleet"sv,     "flicker"sv,   "flint"sv,
    "flock"sv,     "flood"sv,     "florist"sv,   "flour"sv,     "flower"sv,
    "flute"sv,     "flyer"sv,     "foam"sv,      "fog"sv,       "foliage"sv,
    "folly"sv,     "ford"sv,      "forest"sv,    "forge"sv,     "fork"sv,
    "fort"sv,      "fossil"sv,    "fountain"sv,  "fox"sv,       "fractal"sv,
    "fragment"sv,  "fresco"sv,    "friction"sv,  "frigate"sv,   "frog"sv,
    "frost"sv,     "fudge"sv,     "funnel"sv,    "furnace"sv,   "fury"sv,
    "gadget"sv,    "galaxy"sv,    "gale"sv,      "gallery"sv,   "garden"sv,
    "garland"sv,   "garnet"sv,    "gasket"sv,    "gazelle"sv,   "gazebo"sv,
    "gem"sv,       "genius"sv,    "geyser"sv,    "ginger"sv,    "giraffe"sv,
    "glacier"sv,   "glade"sv,     "glider"sv,    "globe"sv,     "gloom"sv,
    "glove"sv,     "glow"sv,      "glue"sv,      "gnome"sv,     "goat"sv,
    "goblet"sv,    "goddess"sv,   "gold"sv,      "goose"sv,     "gopher"sv,
    "gorge"sv,     "grain"sv,     "granite"sv,   "grape"sv,     "grass"sv,
    "gravel"sv,    "gravy"sv,     "grease"sv,    "grove"sv,     "guilder"sv,
    "gulf"sv,      "gull"sv,      "gum"sv,       "gust"sv,      "habitat"sv,
    "hail"sv,      "hammock"sv,   "hamster"sv,   "harbor"sv,    "harp"sv,
    "harvest"sv,   "hazard"sv,    "haze"sv,      "hazel"sv,     "hearth"sv,
    "heather"sv,   "heaven"sv,    "hedge"sv,     "helix"sv,     "herald"sv,
    "herb"sv,      "herd"sv,      "highland"sv,  "highway"sv,   "hill"sv,
    "hinge"sv,     "hollow"sv,    "holster"sv,   "honey"sv,     "horizon"sv,
    "horn"sv,      "horse"sv,     "hose"sv,      "host"sv,      "hotel"sv,
    "hound"sv,     "hourglass"sv, "hub"sv,       "huckle"sv,    "hue"sv,
    "hull"sv,      "humming"sv,   "hunter"sv,    "hurricane"sv, "hut"sv,
    "hyacinth"sv,  "ibex"sv,      "ibis"sv,      "iceberg"sv,   "igloo"sv,
    "iguana"sv,    "incense"sv,   "inlet"sv,     "insect"sv,    "island"sv,
    "ivory"sv,     "ivy"sv,       "jackal"sv,    "jade"sv,      "jaguar"sv,
    "jasmine"sv,   "javelin"sv,   "jazz"sv,      "jelly"sv,     "jewel"sv,
    "joker"sv,     "journey"sv,   "judo"sv,      "julep"sv,     "jungle"sv,
    "juniper"sv,   "kale"sv,      "kayak"sv,     "keg"sv,       "kestrel"sv,
    "kettle"sv,    "key"sv,       "kiosk"sv,     "kite"sv,      "kitten"sv,
    "kiwi"sv,      "knight"sv,    "knoll"sv,     "knot"sv,      "koala"sv,
    "ladder"sv,    "lagoon"sv,    "lake"sv,      "lamb"sv,      "lamp"sv,
    "lantern"sv,   "lark"sv,      "lasso"sv,     "laurel"sv,    "lavender"sv,
    "lawn"sv,      "leather"sv,   "leek"sv,      "lens"sv,      "leopard"sv,
    "lettuce"sv,   "lichen"sv,    "lilac"sv,     "lily"sv,      "lime"sv,
    "linden"sv,    "line"sv,      "linen"sv,     "link"sv,      "lion"sv,
    "lizard"sv,    "llama"sv,     "lobster"sv,   "lock"sv,      "locust"sv,
    "loft"sv,      "log"sv,       "loom"sv,      "loop"sv,      "lotus"sv,
    "lounge"sv,    "lumber"sv,    "lunar"sv,     "lynx"sv,      "lyric"sv,
    "macaw"sv,     "mackerel"sv,  "madrone"sv,   "magazine"sv,  "magma"sv,
    "magnolia"sv,  "mallard"sv,   "mammoth"sv,   "mango"sv,     "mansion"sv,
    "mantle"sv,    "maple"sv,     "marble"sv,    "marina"sv,    "marrow"sv,
    "marsh"sv,     "mascot"sv,    "mason"sv,     "meadow"sv,    "meadow"sv,
    "medal"sv,     "meerkat"sv,   "mellow"sv,    "melon"sv,     "mercury"sv,
    "meridian"sv,  "mesh"sv,      "mews"sv,      "mica"sv,      "mimic"sv,
    "minnow"sv,    "mint"sv,      "mirror"sv,    "mist"sv,      "mistle"sv,
    "mocha"sv,     "model"sv,     "mohair"sv,    "mole"sv,      "monarch"sv,
    "monk"sv,      "monsoon"sv,   "moon"sv,      "moose"sv,     "mosaic"sv,
    "mosque"sv,    "moss"sv,      "moth"sv,      "mountain"sv,  "mouse"sv,
    "mule"sv,      "mural"sv,     "musk"sv,      "mussel"sv,    "mustard"sv,
    "myrtle"sv,    "mystic"sv,    "narcissus"sv, "navel"sv,     "necktie"sv,
    "nectar"sv,    "needle"sv,    "nest"sv,      "newt"sv,      "nickel"sv,
    "night"sv,     "nile"sv,      "noble"sv,     "nomad"sv,     "nozzle"sv,
    "nugget"sv,    "nun"sv,       "nursery"sv,   "nutmeg"sv,    "nylon"sv,
    "nymph"sv,     "oak"sv,       "oasis"sv,     "ocean"sv,     "octave"sv,
    "olive"sv,     "onyx"sv,      "opals"sv,     "oracle"sv,    "orange"sv,
    "orchard"sv,   "orchid"sv,    "oriole"sv,    "osprey"sv,    "ostrich"sv,
    "otter"sv,     "oven"sv,      "owl"sv,       "oxford"sv,    "oxygen"sv,
    "oyster"sv,    "paddle"sv,    "palace"sv,    "palm"sv,      "panda"sv,
    "pane"sv,      "pantry"sv,    "paparazzi"sv, "papaya"sv,    "parade"sv,
    "parcel"sv,    "parch"sv,     "park"sv,      "parrot"sv,    "parsley"sv,
    "passage"sv,   "pasta"sv,     "pastel"sv,    "pasture"sv,   "path"sv,
    "patio"sv,     "pavilion"sv,  "paw"sv,       "pea"sv,       "peach"sv,
    "pearl"sv,     "pebble"sv,    "pelican"sv,   "pen"sv,       "pencil"sv,
    "peninsula"sv, "pepper"sv,    "perch"sv,     "perfume"sv,   "petal"sv,
    "petunia"sv,   "phoenix"sv,   "piano"sv,     "pickle"sv,    "pier"sv,
    "pigeon"sv,    "piglet"sv,    "pillar"sv,    "pillow"sv,    "pilot"sv,
    "pimple"sv,    "pinch"sv,     "pine"sv,      "pink"sv,      "pinto"sv,
    "pioneer"sv,   "piston"sv,    "pitch"sv,     "pixel"sv,     "pizza"sv,
    "plain"sv,     "plank"sv,     "plant"sv,     "plaster"sv,   "plateau"sv,
    "plaza"sv,     "pleat"sv,     "plow"sv,      "plum"sv,      "plume"sv,
    "pocket"sv,    "poem"sv,      "poet"sv,      "point"sv,     "polar"sv,
    "pollen"sv,    "poncho"sv,    "pond"sv,      "pony"sv,      "pool"sv,
    "poplar"sv,    "poppy"sv,     "porch"sv,     "porpoise"sv,  "port"sv,
    "poster"sv,    "potato"sv,    "pouch"sv,     "prairie"sv,   "prawn"sv,
    "prelude"sv,   "preserve"sv,  "prince"sv,    "prism"sv,     "prize"sv,
    "prophet"sv,   "prose"sv,     "prune"sv,     "puddle"sv,    "puffin"sv,
    "pulley"sv,    "pulse"sv,     "pumpkin"sv,   "puma"sv,      "puppet"sv,
    "puzzle"sv,    "pyramid"sv,   "quail"sv,     "quarry"sv,    "quartz"sv,
    "quasar"sv,    "quay"sv,      "quill"sv,     "quilt"sv,     "quince"sv,
    "quiver"sv,    "raccoon"sv,   "radar"sv,     "radish"sv,    "raft"sv,
    "rail"sv,      "rainbow"sv,   "raisin"sv,    "ramp"sv,      "ranch"sv,
    "rand"sv,      "range"sv,     "rapid"sv,     "rasp"sv,      "raven"sv,
    "ravine"sv,    "rayon"sv,     "recess"sv,    "reef"sv,      "reel"sv,
    "refuge"sv,    "regent"sv,    "relish"sv,    "resin"sv,     "resort"sv,
    "revolt"sv,    "rhapsody"sv,  "rheum"sv,     "rhino"sv,     "rhythm"sv,
    "ribbon"sv,    "ridge"sv,     "rift"sv,      "ring"sv,      "river"sv,
    "robin"sv,     "robot"sv,     "rocket"sv,    "rodeo"sv,     "rogue"sv,
    "roller"sv,    "rook"sv,      "rose"sv,      "roster"sv,    "round"sv,
    "route"sv,     "rover"sv,     "ruby"sv,      "rudder"sv,    "rug"sv,
    "ruin"sv,      "ruler"sv,     "rumor"sv,     "rune"sv,      "ruse"sv,
    "rust"sv,      "rye"sv,       "sable"sv,     "saddle"sv,    "safari"sv,
    "sage"sv,      "sail"sv,      "salamander"sv,"salmon"sv,    "salon"sv,
    "salsa"sv,     "sample"sv,    "sand"sv,      "sapphire"sv,  "sardine"sv,
    "sauna"sv,     "savanna"sv,   "saw"sv,       "scallop"sv,   "scarf"sv,
    "scenery"sv,   "scepter"sv,   "scholar"sv,   "scone"sv,     "scoop"sv,
    "scorpion"sv,  "scout"sv,     "scrap"sv,     "screen"sv,    "scroll"sv,
    "scrub"sv,     "sculpt"sv,    "seal"sv,      "seam"sv,      "seaweed"sv,
    "sector"sv,    "sedan"sv,     "seed"sv,      "senate"sv,    "sequel"sv,
    "serpent"sv,   "serval"sv,    "settle"sv,    "shack"sv,     "shade"sv,
    "shadow"sv,    "shaft"sv,     "shale"sv,     "shaman"sv,    "shard"sv,
    "shark"sv,     "shed"sv,      "sheep"sv,     "sheer"sv,     "shelf"sv,
    "shell"sv,     "sherbet"sv,   "shield"sv,    "shift"sv,     "shingle"sv,
    "ship"sv,      "shire"sv,     "shirt"sv,     "shock"sv,     "shore"sv,
    "shrine"sv,    "shrub"sv,     "sierra"sv,    "signet"sv,    "silence"sv,
    "silk"sv,      "sill"sv,      "silver"sv,    "sinew"sv,     "siren"sv,
    "sister"sv,    "sizzle"sv,    "skate"sv,     "skeleton"sv,  "sketch"sv,
    "skiff"sv,     "skull"sv,     "skunk"sv,     "sky"sv,       "slate"sv,
    "sledge"sv,    "sleep"sv,     "sleet"sv,     "slicer"sv,    "slider"sv,
    "slime"sv,     "slope"sv,     "sloth"sv,     "smoke"sv,     "snail"sv,
    "snake"sv,     "snap"sv,      "snipe"sv,     "snooze"sv,    "snow"sv,
    "soap"sv,      "sock"sv,      "soda"sv,      "sofa"sv,      "solar"sv,
    "sole"sv,      "solstice"sv,  "sombrero"sv,  "sonar"sv,     "sorbet"sv,
    "sorrel"sv,    "souffle"sv,   "soup"sv,      "spa"sv,       "spark"sv,
    "sparrow"sv,   "spell"sv,     "sphere"sv,    "spice"sv,     "spider"sv,
    "spine"sv,     "spiral"sv,    "spirit"sv,    "splash"sv,    "spleen"sv,
    "sponge"sv,    "spoon"sv,     "spore"sv,     "spring"sv,    "sprout"sv,
    "spruce"sv,    "spur"sv,      "squash"sv,    "squid"sv,     "squirrel"sv,
    "stable"sv,    "stadium"sv,   "stair"sv,     "stall"sv,     "stamp"sv,
    "star"sv,      "starch"sv,    "starlight"sv, "starling"sv,  "steam"sv,
    "steed"sv,     "steel"sv,     "steeple"sv,   "stellar"sv,   "stem"sv,
    "stencil"sv,   "stew"sv,      "stilt"sv,     "sting"sv,     "stirrup"sv,
    "stitch"sv,    "stock"sv,     "stole"sv,     "stone"sv,     "stool"sv,
    "storm"sv,     "stove"sv,     "strand"sv,    "strata"sv,    "stream"sv,
    "street"sv,    "strike"sv,    "string"sv,    "stripe"sv,    "stroke"sv,
    "stroll"sv,    "stub"sv,      "studio"sv,    "stump"sv,     "sturgeon"sv,
    "subway"sv,    "sugar"sv,     "suit"sv,      "suite"sv,     "sultan"sv,
    "summit"sv,    "sunbeam"sv,   "sunset"sv,    "surf"sv,      "surge"sv,
    "sushi"sv,     "swallow"sv,   "swamp"sv,     "swan"sv,      "sweater"sv,
    "sweep"sv,     "sweet"sv,     "swift"sv,     "swing"sv,     "switch"sv,
    "sword"sv,     "syrup"sv,     "table"sv,     "taboo"sv,     "taco"sv,
    "talent"sv,    "tanker"sv,    "tapestry"sv,  "tapir"sv,     "tarpon"sv,
    "tassel"sv,    "tavern"sv,    "teak"sv,      "teapot"sv,    "temple"sv,
    "tenant"sv,    "tender"sv,    "tent"sv,      "tepee"sv,     "term"sv,
    "terra"sv,     "textile"sv,   "thaw"sv,      "theater"sv,   "thicket"sv,
    "thistle"sv,   "thorn"sv,     "throne"sv,    "thunder"sv,   "tide"sv,
    "tiger"sv,     "timber"sv,    "tinsel"sv,    "tissue"sv,    "toast"sv,
    "tobacco"sv,   "toffee"sv,    "toga"sv,      "toilet"sv,    "token"sv,
    "tomato"sv,    "tomb"sv,      "tome"sv,      "tongue"sv,    "tonic"sv,
    "tool"sv,      "tooth"sv,     "topaz"sv,     "topic"sv,     "torch"sv,
    "tornado"sv,   "tortoise"sv,  "toucan"sv,    "towel"sv,     "tower"sv,
    "town"sv,      "toxin"sv,     "toy"sv,       "trail"sv,     "train"sv,
    "tram"sv,      "trap"sv,      "trash"sv,     "tray"sv,      "treasure"sv,
    "treaty"sv,    "trench"sv,    "triangle"sv,  "tribute"sv,   "trick"sv,
    "trident"sv,   "trillium"sv,  "trinket"sv,   "tripod"sv,    "troll"sv,
    "troop"sv,     "trophy"sv,    "trot"sv,      "trout"sv,     "truck"sv,
    "trumpet"sv,   "trunk"sv,     "trust"sv,     "truth"sv,     "tugboat"sv,
    "tulip"sv,     "tumble"sv,    "tuna"sv,      "tundra"sv,    "tunnel"sv,
    "turban"sv,    "turkey"sv,    "turnip"sv,    "turret"sv,    "turtle"sv,
    "tusk"sv,      "tuxedo"sv,    "twig"sv,      "twilight"sv,  "twin"sv,
    "twine"sv,     "twist"sv,     "typhoon"sv,   "udder"sv,     "umbrella"sv,
    "uncle"sv,     "unicorn"sv,   "uniform"sv,   "urn"sv,       "valley"sv,
    "vapor"sv,     "vault"sv,     "veil"sv,      "velvet"sv,    "vendor"sv,
    "venom"sv,     "vent"sv,      "veranda"sv,   "verdant"sv,   "verge"sv,
    "vernal"sv,    "verse"sv,     "vessel"sv,    "vest"sv,      "veteran"sv,
    "viaduct"sv,   "vibe"sv,      "violet"sv,    "violin"sv,    "viper"sv,
    "virtue"sv,    "visa"sv,      "vista"sv,     "vixen"sv,     "vocal"sv,
    "vodka"sv,     "vogue"sv,     "voice"sv,     "volcano"sv,   "volley"sv,
    "vortex"sv,    "voucher"sv,   "voyage"sv,    "vulture"sv,   "wade"sv,
    "wagon"sv,     "waist"sv,     "wall"sv,      "wallet"sv,    "walnut"sv,
    "walrus"sv,    "waltz"sv,     "wand"sv,      "warbler"sv,   "ward"sv,
    "warmth"sv,    "warren"sv,    "warrior"sv,   "wasp"sv,      "watch"sv,
    "water"sv,     "wattle"sv,    "wave"sv,      "wax"sv,       "weapon"sv,
    "weasel"sv,    "weather"sv,   "weaver"sv,    "web"sv,       "wedge"sv,
    "weed"sv,      "weir"sv,      "whale"sv,     "wheat"sv,     "wheel"sv,
    "whelp"sv,     "whip"sv,      "whisper"sv,   "whistle"sv,   "wick"sv,
    "willow"sv,    "wind"sv,      "window"sv,    "wine"sv,      "wing"sv,
    "winter"sv,    "wisp"sv,      "witch"sv,     "witness"sv,   "wizard"sv,
    "wolf"sv,      "wombat"sv,    "wood"sv,      "wool"sv,      "word"sv,
    "workshop"sv,  "worm"sv,      "wreath"sv,    "wreck"sv,     "wren"sv,
    "wrench"sv,    "wrist"sv,     "xenon"sv,     "xylophone"sv, "yacht"sv,
    "yak"sv,       "yam"sv,       "yarn"sv,      "yogurt"sv,    "yoke"sv,
    "youth"sv,     "zebra"sv,     "zenith"sv,    "zephyr"sv,    "zinc"sv,
    "zipper"sv,    "zone"sv,      "zoo"sv,       "zoom"sv,
};

constexpr std::array kVerbs{
    "amble"sv,  "bake"sv,    "bask"sv,    "blaze"sv,   "bloom"sv,   "blossom"sv,
    "bounce"sv, "bow"sv,     "branch"sv,  "breathe"sv, "brush"sv,   "bubble"sv,
    "build"sv,  "burrow"sv,  "buzz"sv,    "carve"sv,   "chase"sv,   "chime"sv,
    "churn"sv,  "climb"sv,   "coast"sv,   "crackle"sv, "crawl"sv,   "creak"sv,
    "crest"sv,  "crisp"sv,   "crouch"sv,  "cruise"sv,  "crunch"sv,  "dance"sv,
    "dart"sv,   "dash"sv,    "delve"sv,   "dip"sv,     "dive"sv,    "dodge"sv,
    "draft"sv,  "drain"sv,   "drape"sv,   "dredge"sv,  "drench"sv,  "drift"sv,
    "drink"sv,  "drizzle"sv, "drop"sv,    "drum"sv,    "dwell"sv,   "echo"sv,
    "emerge"sv, "fade"sv,    "fall"sv,    "fashion"sv, "ferry"sv,   "fizz"sv,
    "flame"sv,  "flap"sv,    "flash"sv,   "flatten"sv, "flick"sv,   "fling"sv,
    "flip"sv,   "float"sv,   "flock"sv,   "flood"sv,   "flourish"sv,"flow"sv,
    "flutter"sv,"foam"sv,    "forge"sv,   "fray"sv,    "frisk"sv,   "frolic"sv,
    "gaze"sv,   "gleam"sv,   "glide"sv,   "glimmer"sv, "glint"sv,   "glisten"sv,
    "glow"sv,   "gnaw"sv,    "graze"sv,   "grow"sv,    "gush"sv,    "hail"sv,
    "halt"sv,   "hammer"sv,  "harden"sv,  "harvest"sv, "hiss"sv,    "hover"sv,
    "howl"sv,   "huddle"sv,  "hug"sv,     "hum"sv,     "hunt"sv,    "hurl"sv,
    "hush"sv,   "ignite"sv,  "jazz"sv,    "jog"sv,     "journey"sv, "jump"sv,
    "kindle"sv, "knit"sv,    "knock"sv,   "lament"sv,  "latch"sv,   "launch"sv,
    "leap"sv,   "lilt"sv,    "linger"sv,  "lodge"sv,   "loom"sv,    "loop"sv,
    "lounge"sv, "lurch"sv,   "lurk"sv,    "march"sv,   "melt"sv,    "merge"sv,
    "mew"sv,    "migrate"sv, "mimic"sv,   "mint"sv,    "moor"sv,    "mosey"sv,
    "munch"sv,  "murmur"sv,  "mute"sv,    "nestle"sv,  "nibble"sv,  "nod"sv,
    "nuzzle"sv, "paddle"sv,  "paint"sv,   "parch"sv,   "pause"sv,   "peck"sv,
    "peer"sv,   "perch"sv,   "pilot"sv,   "pine"sv,    "plod"sv,    "plow"sv,
    "pluck"sv,  "plummet"sv, "plunge"sv,  "polish"sv,  "pounce"sv,  "prance"sv,
    "pray"sv,   "preen"sv,   "press"sv,   "probe"sv,   "prod"sv,    "prune"sv,
    "pry"sv,    "pulse"sv,   "pump"sv,    "purr"sv,    "push"sv,    "quest"sv,
    "race"sv,   "ramble"sv,  "rap"sv,     "rapid"sv,   "reap"sv,    "reel"sv,
    "rest"sv,   "ripple"sv,  "rise"sv,    "roam"sv,    "roar"sv,    "rock"sv,
    "roost"sv,  "rotate"sv,  "rove"sv,    "row"sv,     "rub"sv,     "ruffle"sv,
    "rumble"sv, "rush"sv,    "sail"sv,    "scatter"sv, "scoop"sv,   "scorch"sv,
    "scout"sv,  "scrape"sv,  "scrub"sv,   "scurry"sv,  "seal"sv,    "search"sv,
    "settle"sv, "shade"sv,   "shimmer"sv, "shine"sv,   "shiver"sv,  "shock"sv,
    "shout"sv,  "shove"sv,   "shower"sv,  "shred"sv,   "shrink"sv,  "shroud"sv,
    "shrug"sv,  "shush"sv,   "sigh"sv,    "sing"sv,    "sink"sv,    "sketch"sv,
    "skim"sv,   "skip"sv,    "slash"sv,   "sleep"sv,   "slice"sv,   "slide"sv,
    "sling"sv,  "slink"sv,   "slip"sv,    "slope"sv,   "smash"sv,   "smell"sv,
    "smile"sv,  "smoke"sv,   "snap"sv,    "snare"sv,   "sneak"sv,   "sneeze"sv,
    "sniff"sv,  "snip"sv,    "snooze"sv,  "soar"sv,    "spark"sv,   "sparkle"sv,
    "spawn"sv,  "spear"sv,   "spell"sv,   "spill"sv,   "spin"sv,    "splash"sv,
    "splice"sv, "splint"sv,  "sprout"sv,  "spur"sv,    "sputter"sv, "squash"sv,
    "squeak"sv, "squeeze"sv, "staff"sv,   "stall"sv,   "stamp"sv,   "stare"sv,
    "steep"sv,  "steer"sv,   "stem"sv,    "step"sv,    "stew"sv,    "stir"sv,
    "stitch"sv, "stock"sv,   "stomp"sv,   "stoop"sv,   "strain"sv,  "stride"sv,
    "strike"sv, "string"sv,  "stroke"sv,  "stroll"sv,  "stun"sv,    "stutter"sv,
    "suckle"sv, "suffer"sv,  "surf"sv,    "surge"sv,   "swallow"sv, "swarm"sv,
    "sway"sv,   "sweep"sv,   "swell"sv,   "swerve"sv,  "swim"sv,    "swing"sv,
    "swirl"sv,  "switch"sv,  "swivel"sv,  "tackle"sv,  "tap"sv,     "taste"sv,
    "tear"sv,   "tend"sv,    "thaw"sv,    "thrash"sv,  "throb"sv,   "thrust"sv,
    "thump"sv,  "tickle"sv,  "tilt"sv,    "toast"sv,   "toll"sv,    "topple"sv,
    "toss"sv,   "totter"sv,  "touch"sv,   "tow"sv,     "trace"sv,   "tramp"sv,
    "trap"sv,   "travel"sv,  "traverse"sv,"tread"sv,   "tremble"sv, "trim"sv,
    "trip"sv,   "trot"sv,    "truck"sv,   "trudge"sv,  "trumpet"sv, "trust"sv,
    "tumble"sv, "tune"sv,    "turn"sv,    "tutor"sv,   "twirl"sv,   "twist"sv,
    "twitch"sv, "type"sv,    "unfold"sv,  "unite"sv,   "unlock"sv,  "unravel"sv,
    "unroll"sv, "unveil"sv,  "uplift"sv,  "vault"sv,   "venture"sv, "visit"sv,
    "wade"sv,   "wander"sv,  "warm"sv,    "warn"sv,    "warp"sv,    "wash"sv,
    "wave"sv,   "weave"sv,   "wedge"sv,   "weigh"sv,   "whack"sv,   "whisper"sv,
    "whistle"sv,"whittle"sv, "wilt"sv,    "wind"sv,    "wink"sv,    "wipe"sv,
    "wish"sv,   "wobble"sv,  "wonder"sv,  "worship"sv, "wound"sv,   "wrangle"sv,
    "wrap"sv,   "wreck"sv,   "wring"sv,   "wrinkle"sv, "write"sv,   "yawn"sv,
    "yell"sv,   "yield"sv,   "zap"sv,     "zip"sv,     "zoom"sv,
};

auto randomGenerator() -> std::mt19937_64& {
  thread_local std::mt19937_64 generator{std::random_device{}()};
  return generator;
}

auto randomSuffix() -> std::string {
  static constexpr std::string_view kChars = "abcdefghijklmnopqrstuvwxyz0123456789";
  static constexpr int kSuffixLength = 8;
  std::string result(kSuffixLength, ' ');
  auto& gen = randomGenerator();
  std::uniform_int_distribution<size_t> dist(0, kChars.size() - 1);
  for (int i = 0; i < kSuffixLength; ++i) {
    result[i] = kChars[dist(gen)];
  }
  return result;
}

} // namespace

auto GenerateTaskId() -> std::string {
  auto& gen = randomGenerator();
  std::uniform_int_distribution<size_t> adj_dist(0, kAdjectives.size() - 1);
  std::uniform_int_distribution<size_t> noun_dist(0, kNouns.size() - 1);
  std::uniform_int_distribution<size_t> verb_dist(0, kVerbs.size() - 1);

  return std::string{kAdjectives[adj_dist(gen)]} + '_'
       + std::string{kNouns[noun_dist(gen)]} + '_'
       + std::string{kVerbs[verb_dist(gen)]} + '_'
       + randomSuffix();
}

} // namespace carrot::utils