load("//bazel:build_system.bzl", "strij_cc_library")

strij_cc_library(
    name = "result_receiver_storage",
    hdrs = ["result_receiver_storage.hh"],
    visibility = ["//visibility:public"],
)

strij_cc_library(
    name = "http_result_receiver_lib",
    srcs = ["http_result_receiver.cc"],
    hdrs = ["http_result_receiver.hh"],
    visibility = ["//visibility:public"],
    deps = [
        ":result_receiver_storage",
        "//src/core/io:connection_lib",
    ],
)

strij_cc_library(
    name = "node_lib",
    srcs = ["node.cc"],
    hdrs = ["node.hh"],
    visibility = ["//visibility:public"],
    deps = [
        "//src/core/io:connection_lib",
        "//include/strij/event:command_handler_interface",
        "//include/strij/event:completable_interface",
        "//include/strij/event:dispatcher_interface",
        "//src/core/logging:log_lib",
    ],
)

strij_cc_library(
    name = "node_directory_lib",
    srcs = ["node_directory.cc"],
    hdrs = ["node_directory.hh"],
    visibility = ["//visibility:public"],
    deps = [
        ":node_lib",
        "//src/core/io:connection_lib",
        "//include/strij/event:dispatcher_interface",
    ],
)

strij_cc_library(
    name = "gateway_http_handler_lib",
    srcs = ["gateway_http_handler.cc"],
    hdrs = ["gateway_http_handler.hh"],
    visibility = ["//visibility:public"],
    deps = [
        ":node_directory_lib",
        ":result_receiver_storage",
        "//api/core/task:task_cc_proto",
        "//src/core/io:connection_lib",
        "//src/core/io:llhttp_parser_lib",
        "//src/core/io:tlv_frame",
        "//src/core/logging:log_lib",
        "//src/core/utils:task_id_lib",
    ],
)

strij_cc_library(
    name = "gateway_tlv_handler_lib",
    srcs = ["gateway_tlv_handler.cc"],
    hdrs = ["gateway_tlv_handler.hh"],
    visibility = ["//visibility:public"],
    deps = [
        ":result_receiver_storage",
        "//api/core/task:task_cc_proto",
        "//src/core/io:connection_lib",
        "//src/core/io:tlv_frame",
        "//src/core/logging:log_lib",
    ],
)
