load("//bazel:build_system.bzl", "strij_cc_library")

strij_cc_library(
    name = "admission_controller_interface",
    hdrs = ["admission_controller.hh"],
    visibility = ["//visibility:public"],
    deps = [
        "//api/common/node:node_cc_proto",
        "//include/strij/common:pure_lib",
        "@abseil-cpp//absl/status:status",
    ],
)

strij_cc_library(
    name = "function_resolver_interface",
    hdrs = ["function_resolver.hh"],
    visibility = ["//visibility:public"],
    deps = [
        "//include/strij/common:pure_lib",
        "@abseil-cpp//absl/status:statusor",
    ],
)

strij_cc_library(
    name = "run_task_service_interface",
    hdrs = ["run_task_service.hh"],
    visibility = ["//visibility:public"],
    deps = [
        "//api/common/task:task_cc_proto",
        "//include/strij/common:pure_lib",
    ],
)
