load("//bazel:build_system.bzl", "strij_cc_library")

strij_cc_library(
    name = "admission_controller_interface",
    hdrs = ["admission_controller.hh"],
    visibility = ["//visibility:public"],
    deps = [
        "//api/common/node:node_cc_proto",
        "//include/strij/common:pure_lib",
        "//include/strij/event:command_handler_interface",
        "@abseil-cpp//absl/status:status",
    ],
)

strij_cc_library(
    name = "function_resolver_interface",
    hdrs = ["function_resolver.hh"],
    visibility = ["//visibility:public"],
    deps = [
        "//include/strij/common:pure_lib",
        "@abseil-cpp//absl/status:statusor",
    ],
)

strij_cc_library(
    name = "run_task_service_interface",
    hdrs = ["run_task_service.hh"],
    visibility = ["//visibility:public"],
    deps = [
        "//api/common/task:task_cc_proto",
        "//include/strij/common:pure_lib",
    ],
)

strij_cc_library(
    name = "object_cache_interface",
    hdrs = ["object_cache.hh"],
    visibility = ["//visibility:public"],
    deps = [
        "//api/common/task:task_cc_proto",
        "//include/strij/common:pure_lib",
    ],
)

strij_cc_library(
    name = "child_task_submitter_interface",
    hdrs = ["child_task_submitter.hh"],
    visibility = ["//visibility:public"],
    deps = [
        "//api/common/task:task_cc_proto",
        "//include/strij/common:pure_lib",
        "//include/strij/gateway:result_receiver_storage_interface",
    ],
)

strij_cc_library(
    name = "child_task_forwarder_interface",
    hdrs = ["child_task_forwarder.hh"],
    visibility = ["//visibility:public"],
    deps = [
        "//api/common/task:task_cc_proto",
        "//include/strij/common:pure_lib",
        "@abseil-cpp//absl/status",
    ],
)

strij_cc_library(
    name = "task_handlers_interface",
    hdrs = ["task_handlers.hh"],
    visibility = ["//visibility:public"],
    deps = [
        "//api/common/node:node_cc_proto",
        "//api/common/task:task_cc_proto",
        "//include/strij/common:pure_lib",
        "//include/strij/event:dispatcher_interface",
        "//include/strij/nodeagent:child_task_submitter_interface",
        "//include/strij/nodeagent:function_resolver_interface",
        "@abseil-cpp//absl/status:statusor",
        "@protobuf",
    ],
)
