load("@protobuf//bazel:cc_proto_library.bzl", "cc_proto_library")
load("@rules_proto//proto:defs.bzl", "proto_library")

proto_library(
    name = "config_proto",
    srcs = [
        "extensions.proto",
        "gateway.proto",
        "nodeagent.proto",
        "options.proto",
    ],
    strip_import_prefix = "/api",
    visibility = ["//visibility:public"],
    deps = [
        "//api/core/node:node_proto",
        "@protobuf//:any_proto",
        "@protobuf//:descriptor_proto",
        "@protobuf//:duration_proto",
    ],
)

cc_proto_library(
    name = "config_cc_proto",
    visibility = ["//visibility:public"],
    deps = [":config_proto"],
)
