load("//bazel:build_system.bzl", "carrot_cc_binary")

carrot_cc_binary(
    name = "gateway",
    srcs = ["gateway.cc"],
    deps = [
        "//src/core/common:signal_monitor_lib",
        "//src/core/config:config_loader_lib",
        "//src/core/config/proto:config_cc_proto",
        "//src/core/event:dispatcher_impl_lib",
        "//src/core/io:echo_result_receiver_lib",
        "//src/core/io:gateway_http_handler_lib",
        "//src/core/io:gateway_tlv_handler_lib",
        "//src/core/io:llhttp_parser_lib",
        "//src/core/io:node_directory_lib",
        "//src/core/io:tcp_listener_lib",
        "//src/core/io:tlv_parser_lib",
        "//src/core/logging:log_lib",
        "@abseil-cpp//absl/flags:parse",
    ],
)
