load("//bazel:build_system.bzl", "strij_cc_binary")

strij_cc_binary(
    name = "gateway",
    srcs = ["gateway.cc"],
    deps = [
        "//src/core/common:signal_monitor_lib",
        "//src/core/config:config_loader_lib",
        "//api/core/config:config_cc_proto",
        "//api/core/task:task_cc_proto",
        "//src/core/event:dispatcher_impl_lib",
        "//src/core/extensions:extension_registry_lib",
        "//src/core/extensions:factory_context_lib",
        "//src/core/gateway:exact_state_tracker_lib",
        "//src/core/gateway:http_result_receiver_lib",
        "//src/core/gateway:gateway_http_handler_lib",
        "//src/core/gateway:gateway_tlv_handler_lib",
        "//src/core/gateway:node_directory_lib",
        "//src/core/io:llhttp_parser_lib",
        "//src/core/io:tcp_listener_lib",
        "//src/core/io:tlv_parser_lib",
        "//src/core/logging:log_lib",
        "//src/extensions/node_discovery:node_discovery_interface",
        "//src/extensions/node_discovery/static:static_node_discovery_lib",
        "//src/extensions/schedulers:scheduler_interface",
        "//src/extensions/schedulers/capability_aware:capability_aware_scheduler_lib",
        "//src/extensions/schedulers/round_robin:round_robin_scheduler_lib",
        "@abseil-cpp//absl/flags:parse",
        "@protobuf//:protobuf",
    ],
)
