load("//bazel:build_system.bzl", "strij_cc_library")

strij_cc_library(
    name = "scheduler_router_lib",
    srcs = ["scheduler_router.cc"],
    hdrs = ["scheduler_router.hh"],
    visibility = ["//visibility:public"],
    deps = [
        "//api/common/task:task_cc_proto",
        "//api/gateway/config:gateway_config_cc_proto",
        "//include/strij/extensions:factory_context_lib",
        "//include/strij/extensions:scheduler_interface",
        "//src/common/core/io:connection_lib",
        "//src/common/core/io:tlv_frame",
        "//src/common/extensions:scheduler_loader_lib",
        "//src/gateway/core:node_connection_result_receiver_lib",
        "//src/gateway/core:node_lib",
        "//src/gateway/core:result_receiver_storage",
        "@abseil-cpp//absl/status",
        "@abseil-cpp//absl/status:statusor",
        "@abseil-cpp//absl/strings",
    ],
)
