load("//bazel:build_system.bzl", "strij_cc_test")

strij_cc_test(
    name = "jq_evaluator_test",
    srcs = ["jq_evaluator_test.cc"],
    deps = [
        "//include/strij/extensions:extension_registry_lib",
        "//src/common/extensions/evaluators/jq:jq_evaluator_lib",
        "@abseil-cpp//absl/status",
        "@googletest//:gtest_main",
    ],
)
