load("//bazel:build_system.bzl", "strij_cc_test")

strij_cc_test(
    name = "echo_task_handler_test",
    srcs = ["echo_task_handler_test.cc"],
    deps = [
        "//api/core/task:task_cc_proto",
        "//src/extensions/task_handlers/echo:echo_task_handler_lib",
        "//test/mocks/extensions:extensions_mocks_lib",
        "@googletest//:gtest_main",
    ],
)
