load("//bazel:build_system.bzl", "strij_cc_library")

strij_cc_library(
    name = "signal_monitor_lib",
    srcs = ["signal_monitor.cc"],
    hdrs = ["signal_monitor.hh"],
    visibility = ["//visibility:public"],
    deps = [
        "//include/strij/event:completable_interface",
        "//include/strij/event:dispatcher_interface",
        "//src/core/logging:log_lib",
    ],
)
