load("//bazel:build_system.bzl", "strij_cc_library")

strij_cc_library(
    name = "capability_aware_scheduler_lib",
    srcs = ["capability_aware_scheduler.cc"],
    hdrs = ["capability_aware_scheduler.hh"],
    visibility = ["//visibility:public"],
    deps = [
        "//api/core/node:node_cc_proto",
        "//api/core/task:task_cc_proto",
        "//api/extensions/schedulers/capability_aware:capability_aware_scheduler_cc_proto",
        "//src/core/extensions:extension_registry_lib",
        "//src/core/extensions:factory_context_lib",
        "//src/core/gateway:node_directory_lib",
        "//src/core/gateway:result_receiver_storage",
        "//src/core/io:connection_lib",
        "//src/core/io:tlv_frame",
        "//src/extensions/schedulers:scheduler_interface",
    ],
    alwayslink = True,
)
