load("//bazel:build_system.bzl", "strij_cc_library")

strij_cc_library(
    name = "extension_registry_lib",
    hdrs = ["extension_registry.hh"],
    visibility = ["//visibility:public"],
)

strij_cc_library(
    name = "factory_context_lib",
    srcs = ["factory_context.cc"],
    hdrs = ["factory_context.hh"],
    visibility = ["//visibility:public"],
    deps = [
        "//include/strij/event:dispatcher_interface",
        "//src/core/logging:log_lib",
    ],
)
