load("//bazel:build_system.bzl", "carrot_cc_library")

carrot_cc_library(
    name = "config_loader_lib",
    srcs = ["config_loader.cc"],
    hdrs = ["config_loader.hh"],
    deps = [
        "//api/core/config:config_cc_proto",
        "//src/core/logging:log_lib",
        "@yaml_cpp//:yaml_cpp",
        "@abseil-cpp//absl/flags:parse",
        "@abseil-cpp//absl/flags:usage",
        "@abseil-cpp//absl/status",
        "@abseil-cpp//absl/status:statusor",
        "@abseil-cpp//absl/strings",
        "@protobuf//:protobuf",
    ],
    visibility = ["//visibility:public"],
)