load("//bazel:build_system.bzl", "strij_cc_library")

strij_cc_library(
    name = "scheduler_interface",
    srcs = ["scheduler.cc"],
    hdrs = ["scheduler.hh"],
    visibility = ["//visibility:public"],
    deps = [
        "//api/core/config:config_cc_proto",
        "//api/core/task:task_cc_proto",
        "//include/strij/common:pure_lib",
        "//src/core/extensions:extension_registry_lib",
        "//src/core/extensions:factory_context_lib",
        "//src/core/gateway:result_receiver_storage",
        "//src/core/io:connection_lib",
        "//src/core/io:tlv_frame",
        "@abseil-cpp//absl/status",
        "@abseil-cpp//absl/status:statusor",
        "@abseil-cpp//absl/strings",
        "@protobuf",
    ],
)
