load("//bazel:build_system.bzl", "strij_cc_test")

strij_cc_test(
    name = "workflow_task_handler_test",
    srcs = ["workflow_task_handler_test.cc"],
    deps = [
        "//api/common/node:node_cc_proto",
        "//api/common/task:task_cc_proto",
        "//api/nodeagent/extensions/task_handlers/workflow:workflow_cc_proto",
        "//include/strij/extensions:extension_registry_lib",
        "//src/nodeagent/core:admission_controller_lib",
        "//src/nodeagent/core:child_scheduler_router_lib",
        "//src/nodeagent/core:child_submission_service_lib",
        "//src/nodeagent/core:local_receiver_registry_lib",
        "//src/nodeagent/core:run_task_service_lib",
        "//src/nodeagent/core:task_handler_manager_lib",
        "//src/nodeagent/extensions/schedulers/push:push_local_scheduler_lib",
        "//src/nodeagent/extensions/task_handlers/echo:echo_task_handler_lib",
        "//src/nodeagent/extensions/task_handlers/workflow:workflow_task_handler_lib",
        "//test/mocks/event:event_mocks_lib",
        "//test/mocks/extensions:extensions_mocks_lib",
        "@googletest//:gtest_main",
        "@protobuf//:protobuf",
    ],
)