load("//bazel:build_system.bzl", "strij_cc_library")

strij_cc_library(
    name = "push_local_scheduler_lib",
    srcs = ["push_local_scheduler.cc"],
    hdrs = ["push_local_scheduler.hh"],
    visibility = ["//visibility:public"],
    deps = [
        "//api/common/task:task_cc_proto",
        "//api/nodeagent/extensions/schedulers/push:push_scheduler_cc_proto",
        "//include/strij/event:command_handler_interface",
        "//src/common/extensions:extension_registry_lib",
        "//src/common/core/io:connection_lib",
        "//src/common/core/io:tlv_frame",
        "//src/common/core/logging:log_lib",
        "//src/nodeagent/core:run_task_service_lib",
        "//src/common/extensions:scheduler_interface",
    ],
    alwayslink = True,
)