load("@protobuf//bazel:cc_proto_library.bzl", "cc_proto_library")
load("@rules_proto//proto:defs.bzl", "proto_library")

proto_library(
    name = "jq_proto",
    srcs = ["jq.proto"],
    strip_import_prefix = "/api",
    visibility = ["//visibility:public"],
)

cc_proto_library(
    name = "jq_cc_proto",
    visibility = ["//visibility:public"],
    deps = [":jq_proto"],
)
