load("@rules_proto//proto:defs.bzl", "proto_library")
load("@protobuf//bazel:cc_proto_library.bzl", "cc_proto_library")

proto_library(
    name = "config_proto",
    srcs = [
        "extensions.proto",
        "gateway.proto",
        "nodeagent.proto",
        "options.proto",
    ],
    deps = [
        "@protobuf//:any_proto",
        "@protobuf//:duration_proto",
        "@protobuf//:descriptor_proto",
    ],
    import_prefix = "",
    strip_import_prefix = "",
    visibility = ["//visibility:public"],
)

cc_proto_library(
    name = "config_cc_proto",
    deps = [":config_proto"],
    visibility = ["//visibility:public"],
)