load("//bazel:build_system.bzl", "strij_cc_test")

strij_cc_test(
    name = "function_resolver_test",
    srcs = ["function_resolver_test.cc"],
    deps = [
        "//src/core/extensions:factory_context_lib",
        "//src/core/extensions:function_resolver_lib",
        "//test/mocks/event:event_mocks_lib",
        "@googletest//:gtest_main",
    ],
)
