load("//bazel:build_system.bzl", "carrot_cc_test")

carrot_cc_test(
    name = "tlv_parser_test",
    srcs = ["tlv_parser_test.cc"],
    deps = [
        "//src/core/io:tlv_frame",
        "//src/core/io:tlv_parser_lib",
        "@googletest//:gtest_main",
    ],
)

carrot_cc_test(
    name = "llhttp_parser_test",
    srcs = ["llhttp_parser_test.cc"],
    deps = [
        "//src/core/io:llhttp_parser_lib",
        "@googletest//:gtest_main",
    ],
)

carrot_cc_test(
    name = "tlv_frame_test",
    srcs = ["tlv_frame_test.cc"],
    deps = [
        "//api/core/task:task_cc_proto",
        "//src/core/io:tlv_frame",
        "//src/core/io:tlv_parser_lib",
        "@googletest//:gtest_main",
    ],
)

carrot_cc_test(
    name = "connection_test",
    srcs = ["connection_test.cc"],
    deps = [
        "//src/core/io:connection_lib",
        "//src/core/io:protocol_parser",
        "//test/mocks/common:common_mocks_lib",
        "//test/mocks/event:event_mocks_lib",
        "@googletest//:gtest_main",
    ],
)


