load("//bazel:build_system.bzl", "carrot_cc_test")

carrot_cc_test(
    name = "tlv_parser_test",
    srcs = ["tlv_parser_test.cc"],
    deps = [
        "//src/core/io:tlv_frame",
        "//src/core/io:tlv_parser_lib",
        "@googletest//:gtest_main",
    ],
)

carrot_cc_test(
    name = "gateway_test",
    srcs = ["gateway_test.cc"],
    deps = [
        "//src/core/io:gateway_http_handler_lib",
        "//src/core/io:gateway_tlv_handler_lib",
        "//src/core/io:nodeagent_tlv_handler_lib",
        "//src/core/io:result_receiver_storage",
        "//src/core/io:tlv_frame",
        "//src/core/io:tlv_parser_lib",
        "//test/mocks/event:event_mocks_lib",
        "@googletest//:gtest_main",
    ],
)
