load("//bazel:build_system.bzl", "strij_cc_test")

strij_cc_test(
    name = "evaluator_loader_test",
    srcs = ["evaluator_loader_test.cc"],
    deps = [
        "//api/common/config:config_cc_proto",
        "//api/common/extensions/evaluators/jq:jq_cc_proto",
        "//include/strij/extensions:extension_registry_lib",
        "//src/common/core/utils:jv_lib",
        "//src/common/extensions/evaluators/jq:jq_evaluator_lib",
        "//src/common/loaders:evaluator_loader_lib",
        "@abseil-cpp//absl/status",
        "@abseil-cpp//absl/status:statusor",
        "@googletest//:gtest_main",
    ],
)

strij_cc_test(
    name = "scheduler_factory_test",
    srcs = ["scheduler_factory_test.cc"],
    deps = [
        "//api/common/config:config_cc_proto",
        "//api/gateway/extensions/schedulers/round_robin:round_robin_scheduler_cc_proto",
        "//include/strij/extensions:scheduler_interface",
        "//src/common/loaders:scheduler_loader_lib",
        "//src/gateway/core:node_directory_lib",
        "//src/gateway/core:result_receiver_storage",
        "//src/gateway/extensions/schedulers/round_robin:round_robin_scheduler_lib",
        "//test/mocks/common:common_mocks_lib",
        "//test/mocks/event:event_mocks_lib",
        "//test/mocks/extensions:extensions_mocks_lib",
        "@abseil-cpp//absl/status",
        "@googletest//:gtest_main",
    ],
)
