load("@protobuf//bazel:cc_proto_library.bzl", "cc_proto_library")
load("@rules_proto//proto:defs.bzl", "proto_library")

proto_library(
    name = "piped_executable_proto",
    srcs = ["piped_executable.proto"],
    strip_import_prefix = "/api",
    visibility = ["//visibility:public"],
)

cc_proto_library(
    name = "piped_executable_cc_proto",
    visibility = ["//visibility:public"],
    deps = [":piped_executable_proto"],
)
