load("//bazel:build_system.bzl", "strij_cc_library")

strij_cc_library(
    name = "capability_aware_scheduler_lib",
    srcs = ["capability_aware_scheduler.cc"],
    hdrs = ["capability_aware_scheduler.hh"],
    visibility = [
        "//src/gateway/exe:__pkg__",
        "//test:__subpackages__",
    ],
    deps = [
        "//api/common/node:node_cc_proto",
        "//api/common/task:task_cc_proto",
        "//api/gateway/extensions/schedulers/capability_aware:capability_aware_scheduler_cc_proto",
        "//include/strij/extensions:extension_registry_lib",
        "//include/strij/extensions:factory_context_lib",
        "//include/strij/extensions:scheduler_interface",
        "//src/common/core/io:connection_lib",
        "//src/common/core/io:tlv_frame",
        "//src/gateway/core:node_directory_lib",
        "//src/gateway/core:result_receiver_storage",
    ],
    alwayslink = True,
)
